### ISSUE TITLE
Error on start game

### ISSUE THREAD

**Issue by liuxueyang** [sebity/asteroid-wars#1]
I start game with `(asteroid-wars:start)`, the game windows appears. Then I press Space. And there is error on sbcl-repl: 

>  debugger invoked on a SIMPLE-TYPE-ERROR in thread
> # <THREAD "main thread" RUNNING {1002AAC613}>:
> 
>   The value of LISPBUILDER-SDL::P1 is (524
>                                        404), which is not of type LISPBUILDER-SDL:POINT.
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
>   restarts (invokable by number or by possibly-abbreviated name):
>   0: [STORE-VALUE] Supply a new value for LISPBUILDER-SDL::P1.
>   1: [ABORT      ] Exit debugger, returning to top level.
>   (SB-KERNEL:CHECK-TYPE-ERROR LISPBUILDER-SDL::P1 (524 404) LISPBUILDER-SDL:POINT NIL)
> 0] 

And the Game did not start. I don't know why. Do you know how to fix this. Thank you :-)

**Comment by sebity** [comment]
Can you tell me which Operating System and version you are using, as well as the version of SBCL instead please?

Thanks

Jan

**Comment by sebity** [comment]
I have disabled the swank continuous monitoring as this sometimes causes problems.  

If you can checkout the latest changes and try again for me.  Let me know if it helps.

Thanks

Jan

**Comment by liuxueyang** [comment]
Hello, my SBCL version is 1.3.1. OS is Arch Linux. Kernel: x86_64 Linux 4.4.5-1ARCH. Thank you :-)

**Comment by sebity** [comment]
I can't seem to replicate the error.  Have you tried updating to the latest version of Lispbuilder-SDL?  You can update via quicklisp by running: 

`(ql:update-all-dists)`

This will update all your packages to the latest versions.

Also, have you tried running Asteroid Wars using the latest changes?

**Comment by liuxueyang** [comment]
Yeah, I have `git pull` your repository and it's up to date. 
It's stange. I try run it on openSUSE Linux and it works fine.
However, when I switch to Arch Linux and `(ql:update-all-dists)`, `git pull`, it still appears the error above :-(. I find that that error appears when I open the game window and press `SPACE`, NOT at the same when I start the game.
Maybe your code is fine. There is something wrong in my Arch Linux though I don't know why by now.

Thank you. Your game is fun :+1: :+1:
